Logging improvements
Tinkoff/kora pull request #141
Opened 2023-05-02 15:29 UTC by GoodforGod

Features:
- Logging enchanted for more modules

2023-06-20 06:23 UTC, eld0727 commented on database/database-common/src/main/java/ru/tinkoff/kora/database/common/telemetry/DefaultDataBaseLogger.java
> +            gen.writeStringField("database", this.dbType);
Я  что то не уверен в полезности этих полей в логе, но при этом они будут занимать место

2023-06-20 06:26 UTC, eld0727 commented on http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/Sl4fjHttpClientLogger.java
> +import javax.annotation.Nullable;
А мы в итоге javax или jakarta пользуемся?

2023-06-20 06:31 UTC, eld0727 requested changes

2023-06-20 06:31 UTC, eld0727 commented on http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/Slf4jHttpServerLogger.java
> +            var headersString = HttpHeaders.toString(headers);
Кажется такое представление с `\n` будет неудобно читать как в json, так и в plaintext, предлагаю делить по пробелу

2023-06-20 06:31 UTC, eld0727 commented on validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/ValidationContext.java
> +        SimpleViolation.logger.debug("Validation violation on path '{}' with error: {}", path(), message);
А почему по месту не создать логгер? Зачем разносить по классам?

2023-06-20 06:40 UTC, GoodforGod commented on database/database-common/src/main/java/ru/tinkoff/kora/database/common/telemetry/DefaultDataBaseLogger.java
> +            gen.writeStringField("database", this.dbType);
Идея была в том что одновременно можешь зарегистрировать разные DataSource для разных БД в то время как пул может называться дефолтно, чтобы их как то отличать в логах вот так решил выделить их, мб только database оставить без driver

2023-06-20 06:41 UTC, GoodforGod commented on http/http-client-common/src/main/java/ru/tinkoff/kora/http/client/common/telemetry/Sl4fjHttpClientLogger.java
> +import javax.annotation.Nullable;
Везде javax используется на данный момент

2023-06-20 06:42 UTC, GoodforGod commented on http/http-server-common/src/main/java/ru/tinkoff/kora/http/server/common/telemetry/Slf4jHttpServerLogger.java
> +            var headersString = HttpHeaders.toString(headers);
Ну я по аналогии с HttpClient сделал, там вот именно по \n

Можно по пробелу разбить в целом

2023-06-20 06:43 UTC, GoodforGod commented on validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/ValidationContext.java
> +        SimpleViolation.logger.debug("Validation violation on path '{}' with error: {}", path(), message);
Типо в интерфейсе Violation / Validator? Ну тк они public и поле будет наружу торчать чего бы не хотелось делать

2023-07-09 05:49 UTC, eld0727 commented on validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/ValidationContext.java
> +        SimpleViolation.logger.debug("Validation violation on path '{}' with error: {}", path(), message);
понял

2023-07-12 15:44 UTC, eld0727 approved these changes

2023-07-14 20:07 UTC, merged